[toolchain]
anchor_version = "1.0.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
mimir = "J9MZfzQt2LVkdfvqvTRPhcSN41gSmGKDWNVjxUQPxSDR"

[provider]
cluster = "devnet"
wallet = "C:/Users/enliven/.config/solana/talos-deploy.json"

[scripts]
test = "npx tsx tests/mimir.test.ts"
